#!/bin/bash
# Author: Karim Ait-Allaoua
# Commands copied from:https://forums.developer.nvidia.com/t/intel-9260-wifi-on-jetson-nano-jetbot/73360/88 (Thanks chrisnjackson)

git clone https://git.kernel.org/pub/scm/linux/kernel/git/iwlwifi/backport-iwlwifi.git
cd backport-iwlwifi
git checkout release/core46
make defconfig-iwlwifi-public
make -j4
sudo make install
git clone git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
sudo cp linux-firmware/iwlwifi-9260* /lib/firmware/
sudo reboot